import React from "react";
import POSTable from "../../components/KiduTable";
import KiduPrevious from "../../components/KiduPrevious";

const columns = [
  { key: "reportId", label: "Report ID" },
  { key: "reportType", label: "Report Type" },
  { key: "generatedBy", label: "Generated By" },
  { key: "generatedOn", label: "Generated On" },
  { key: "status", label: "Status" },
];

const ReportList: React.FC = () => {
  // ⚡ Dummy report data
  const reportData = [
    {
      reportId: "REP001",
      reportType: "Sales Summary",
      generatedBy: "Admin",
      generatedOn: "2025-10-21",
      status: "Completed",
    },
    {
      reportId: "REP002",
      reportType: "Purchase Summary",
      generatedBy: "Manager",
      generatedOn: "2025-10-20",
      status: "In Progress",
    },
    {
      reportId: "REP003",
      reportType: "Inventory Stock Report",
      generatedBy: "Admin",
      generatedOn: "2025-10-18",
      status: "Completed",
    },
    {
      reportId: "REP004",
      reportType: "Customer Purchase Report",
      generatedBy: "Sales Executive",
      generatedOn: "2025-10-17",
      status: "Completed",
    },
  ];

  return (
    <div className="bg-light" style={{ minHeight: "100vh", padding: "20px" }}>
      <KiduPrevious/>
      <POSTable
        title="Reports"
        columns={columns}
        data={reportData}
        addButtonLabel="Generate New Report"
        viewRoute="/report-view"
        editRoute="/report-edit"
      />
    </div>
  );
};

export default ReportList;
